export const ADD_APPLICANT = 'ADD_APPLICANT';
export const REMOVE_APPLICANT = 'REMOVE_APPLICANT';
export const ADD_DRUG_PACKAGE = 'ADD_DRUG_PACKAGE';
export const REMOVE_DRUG_PACKAGE = 'REMOVE_DRUG_PACKAGE';
export const SET_PLAN_FIELDS = 'SET_PLAN_FIELDS';
export const FIND_PLAN = 'FIND_PLAN';
export const RECEIVE_PLANS = 'RECEIVE_PLANS';
export const REQUEST_PLANS = 'REQUEST_PLANS';
