export const ADD_APPLICANT = 'ADD_APPLICANT';
export const REMOVE_APPLICANT = 'REMOVE_APPLICANT';
export const ADD_DRUG_PACKAGE = 'ADD_DRUG_PACKAGE';
export const REMOVE_DRUG_PACKAGE = 'REMOVE_DRUG_PACKAGE';
